### PR TITLE
First pass at adding lbvserver resource

### PR DESCRIPTION
**Pull request by cheeseplus**
- Added `lbvserver` resource
- Tested against a NITRO 10.5 AMI
- Minor fixes and readability updates to Readme

### CODE REVIEW

**Comment by jjasghar** [comment]
@cheeseplus walked me through this PR and it works swimmingly. :+1:

**Comment by heathsnow** [comment]
I'll take a look at it today!

**Comment by cheeseplus** [comment]
woot!

**Comment by heathsnow** [comment]
LGTM!  :shipit:

**Pull request merged**
